#pkgname="my"
#output="database/my"
add-global-variants=true
add-panic-variants=true 

[mysql]
  dbname  = "portfolio"
  host    = "localhost"
  port    = 3306
  user    = "portfolio"
  pass    = "test"
  sslmode = "false"
  tinyint_as_int = true

[auto-columns]
    created = "createdAt"
    updated = "updatedAt"

