[mysql]
  dbname  = "portfolio"
  host    = "localhost"
  port    = 3306
  user    = "portfolio"
  pass    = "test"
  sslmode = "false"
  tinyint_as_int = true

[auto-columns]
    created = "created"
    