[mysql]
  dbname  = "portfolio"
  host    = "localhost"
  port    = 3306
  user    = "portfolio"
  pass    = "test"
  sslmode = "false"
  tinyint_as_int = true

[auto-columns]
    created = "createdAt"
    updated = "updatedAt"


#pkgname="db"
#output="database/mysql"
#add-global-variants=true
#add-panic-variants=true